# Generated by Django 4.2.19 on 2025-07-17 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, help_text='Relationship to case (e.g. Family, Detective, Advocate)', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Your story, connection, or reason for joining')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('preferred_contact', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=20)),
                ('notifications_tips', models.BooleanField(default=True)),
                ('notifications_updates', models.BooleanField(default=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('other_language', models.CharField(blank=True, help_text="Specify if language is 'Other'", max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
