# Generated by Django 4.2.19 on 2025-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_language',
            field=models.CharField(blank=True, help_text="Specify if language is 'Other'", max_length=50),
        ),
    ]
