# Generated by Django 4.2.19 on 2025-10-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='invite_only_mode',
            field=models.BooleanField(default=True, help_text='Require invite codes for registration'),
        ),
    ]
