# Generated by Django 4.2.19 on 2025-07-03 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
