# Generated by Django 4.2.19 on 2025-09-25 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0002_spotlightflag_spotlightsettings_userviolation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightpost',
            name='event_type',
            field=models.CharField(blank=True, choices=[('none', 'No special event'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('wedding', 'Wedding'), ('graduation', 'Graduation'), ('memorial', 'Memorial Day'), ('achievement', 'Achievement'), ('holiday', 'Holiday')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='spotlightpost',
            name='last_recurring_post',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotlightpost',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_posts', to='spotlight.spotlightpost'),
        ),
        migrations.AddField(
            model_name='spotlightpost',
            name='recurring_yearly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='spotlightpost',
            index=models.Index(fields=['recurring_yearly', 'last_recurring_post'], name='spotlight_s_recurri_97ab99_idx'),
        ),
    ]
