# Generated by Django 4.2.19 on 2025-10-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_leoinvite_remove_investigatorinvite_case_and_more'),
        ('spotlight', '0003_spotlightpost_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightpost',
            name='case',
            field=models.ForeignKey(blank=True, help_text="If null, this is a main site spotlight post. Otherwise, it's a case-specific post.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spotlight_posts_main', to='cases.case'),
        ),
        migrations.AddField(
            model_name='spotlightpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='spotlight/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='spotlightpost',
            index=models.Index(fields=['case', 'status', '-published_at'], name='spotlight_s_case_id_5be0e1_idx'),
        ),
    ]
