# Generated by Django 4.2.19 on 2025-08-08 20:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_logo'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='ml_analysis_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersession',
            name='risk_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('suspicious_user', 'Suspicious User Detected'), ('high_risk', 'High Risk Activity'), ('pattern_detected', 'Pattern Detected'), ('threshold_exceeded', 'Threshold Exceeded'), ('law_enforcement', 'Law Enforcement Alert'), ('system', 'System Alert'), ('ml_detection', 'ML Detection'), ('daily_summary', 'Daily Summary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_alerts', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='devicefingerprint',
            name='associated_cases',
            field=models.ManyToManyField(blank=True, to='cases.case'),
        ),
        migrations.AlterField(
            model_name='suspiciousactivity',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_sessions', to='cases.case'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
