# Generated by Django 4.2.19 on 2026-03-24 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0007_remove_caseinvitation_access_type_and_more'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspiciousactivity',
            name='activity_type',
            field=models.CharField(choices=[('rapid_visits', 'Rapid Visits'), ('unusual_hour', 'Unusual Hour Access'), ('excessive_page_views', 'Excessive Page Views'), ('vpn_usage', 'VPN/Proxy Usage'), ('tor_usage', 'Tor Usage'), ('ip_change', 'IP Address Change'), ('geo_jump', 'Geographic Jump'), ('device_change', 'Device Change'), ('fingerprint_mismatch', 'Fingerprint Mismatch'), ('multiple_devices', 'Multiple Devices'), ('rapid_navigation', 'Rapid Navigation'), ('no_interaction', 'No Interaction'), ('excessive_copying', 'Excessive Copying'), ('data_scraping', 'Data Scraping'), ('form_flooding', 'Form Flooding'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('bot_behavior', 'Bot Behavior'), ('credential_stuffing', 'Credential Stuffing'), ('fake_tip', 'Fake Tip Submission'), ('spam_content', 'Spam Content'), ('harassment', 'Harassment'), ('suspicious_pattern', 'Suspicious Pattern'), ('honeypot_triggered', 'Honeypot Triggered')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('page_exit', 'Page Exit'), ('navigation', 'Navigation'), ('scroll', 'Scroll'), ('visibility_change', 'Visibility Change'), ('click', 'Click'), ('form_submit', 'Form Submit'), ('form_field_focus', 'Form Field Focus'), ('post_view', 'Post View'), ('post_create', 'Post Create'), ('comment', 'Comment'), ('like', 'Like'), ('share', 'Share'), ('copy', 'Copy'), ('download', 'Download'), ('media_view', 'Media View'), ('video_play', 'Video Play'), ('video_pause', 'Video Pause'), ('gallery_open', 'Gallery Open'), ('tip_submit', 'Tip Submit'), ('contact_submit', 'Contact Submit'), ('tip_view', 'Tip View'), ('donation_click', 'Donation Click'), ('donation_complete', 'Donation Complete'), ('donation_cancel', 'Donation Cancel'), ('login_attempt', 'Login Attempt'), ('login_success', 'Login Success'), ('login_fail', 'Login Fail'), ('logout', 'Logout'), ('rapid_navigation', 'Rapid Navigation'), ('vpn_detected', 'VPN Detected'), ('suspicious_pattern', 'Suspicious Pattern'), ('anomaly_detected', 'Anomaly Detected'), ('honeypot_triggered', 'Honeypot Triggered')], db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='MLTrainingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=255)),
                ('label', models.CharField(choices=[('suspect', 'Confirmed Suspect'), ('high_risk', 'High Risk / Investigate'), ('low_risk', 'Low Risk / Monitor'), ('innocent', 'Cleared / Innocent')], max_length=20)),
                ('labeled_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Why this label was assigned')),
                ('cached_features', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_labels', to='cases.case')),
                ('labeled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_labels_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_training_labels',
                'ordering': ['-labeled_at'],
                'unique_together': {('fingerprint_hash', 'case')},
            },
        ),
    ]
