# Generated by Django 4.2.19 on 2025-08-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_logo'),
        ('tracker', '0002_alert_notification_sent_alert_notification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_alerts', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='suspiciousactivity',
            name='activity_type',
            field=models.CharField(choices=[('rapid_visits', 'Rapid Visits'), ('unusual_hour', 'Unusual Hour Access'), ('excessive_page_views', 'Excessive Page Views'), ('vpn_usage', 'VPN/Proxy Usage'), ('tor_usage', 'Tor Usage'), ('ip_change', 'IP Address Change'), ('geo_jump', 'Geographic Jump'), ('device_change', 'Device Change'), ('fingerprint_mismatch', 'Fingerprint Mismatch'), ('multiple_devices', 'Multiple Devices'), ('rapid_navigation', 'Rapid Navigation'), ('no_interaction', 'No Interaction'), ('excessive_copying', 'Excessive Copying'), ('data_scraping', 'Data Scraping'), ('form_flooding', 'Form Flooding'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('bot_behavior', 'Bot Behavior'), ('credential_stuffing', 'Credential Stuffing'), ('fake_tip', 'Fake Tip Submission'), ('spam_content', 'Spam Content'), ('harassment', 'Harassment'), ('suspicious_pattern', 'Suspicious Pattern')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='suspiciousactivity',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_sessions', to='cases.case'),
        ),
    ]
