# Generated by Django 4.2.19 on 2026-03-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_add_ml_training_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='ip_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
