# Generated by Django 4.2.19 on 2025-10-07 02:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0004_leoinvite_remove_investigatorinvite_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('case_submission', 'New Case Submission'), ('press', 'Media/Press')], max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('case_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('responded', 'Responded'), ('archived', 'Archived')], default='new', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_inquiries',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='contact_inq_status_b7ab91_idx'), models.Index(fields=['inquiry_type'], name='contact_inq_inquiry_3b13ea_idx'), models.Index(fields=['submitted_at'], name='contact_inq_submitt_6fee00_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('submitter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submitter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('submitter_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('tip_content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('urgency', models.CharField(choices=[('low', 'Low - General information'), ('medium', 'Medium - Relevant details'), ('high', 'High - Important information'), ('urgent', 'Urgent - Critical information')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('responded', 'Responded'), ('archived', 'Archived')], default='new', max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='cases.case')),
            ],
            options={
                'db_table': 'tips',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['case'], name='tips_case_id_1ff473_idx'), models.Index(fields=['status'], name='tips_status_7df26a_idx'), models.Index(fields=['urgency'], name='tips_urgency_a362b3_idx'), models.Index(fields=['submitted_at'], name='tips_submitt_e4048e_idx')],
            },
        ),
    ]
