# cases/urls.py - Updated URL configuration with all new endpoints

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    CaseViewSet,
    SpotlightPostViewSet,
    TemplateRegistryViewSet,
    CasePhotoViewSet,
    DeploymentLogViewSet
)
from .views import image_upload  # ADD THIS BACK

# Create router and register all viewsets
router = DefaultRouter()

# Your existing registration
router.register(r'cases', CaseViewSet, basename='case')

# New viewset registrations
router.register(r'spotlight-posts', SpotlightPostViewSet, basename='spotlight-post')
router.register(r'templates', TemplateRegistryViewSet, basename='template')
router.register(r'case-photos', CasePhotoViewSet, basename='case-photo')
router.register(r'deployment-logs', DeploymentLogViewSet, basename='deployment-log')

# ACTIVATE THIS - Combine custom endpoint with router URLs
urlpatterns = [
    path('images/upload/', image_upload.upload_image, name='upload_image'),
    path('', include(router.urls)),
]

# ================================================================
# AVAILABLE ENDPOINTS - Generated by the router
# ================================================================
"""
The router automatically creates these endpoints:

CUSTOM ENDPOINTS:
------------------------------------
POST   /images/upload/                      - Upload image for customization

CASES (existing + new actions):
------------------------------------
GET    /cases/                              - List cases
POST   /cases/                              - Create case
GET    /cases/{id}/                         - Get case detail
PUT    /cases/{id}/                         - Update case
PATCH  /cases/{id}/                         - Partial update
DELETE /cases/{id}/                         - Delete case

Custom Case Actions (NEW):
POST   /cases/{id}/save_customizations/     - Save template customizations
POST   /cases/{id}/deploy/                  - Deploy website
GET    /cases/{id}/deployment_status/       - Check deployment status  
POST   /cases/{id}/update_template_section/ - Update specific template section
GET    /cases/my_cases/                     - Get only current user's cases
GET    /cases/stats/                        - Get case statistics

SPOTLIGHT POSTS (NEW):
------------------------------------
GET    /spotlight-posts/                    - List posts (?case_id=xxx to filter)
POST   /spotlight-posts/                    - Create post
GET    /spotlight-posts/{id}/               - Get post detail
PUT    /spotlight-posts/{id}/               - Update post
PATCH  /spotlight-posts/{id}/               - Partial update
DELETE /spotlight-posts/{id}/               - Delete post
POST   /spotlight-posts/{id}/publish/       - Publish post
POST   /spotlight-posts/{id}/schedule/      - Schedule post

TEMPLATES (NEW):
------------------------------------
GET    /templates/                          - List available templates
GET    /templates/{id}/                     - Get template detail
GET    /templates/{id}/schema/              - Get template customization schema
GET    /templates/compare/                  - Compare all templates

CASE PHOTOS (NEW):
------------------------------------
GET    /case-photos/                        - List photos (?case_id=xxx to filter)
POST   /case-photos/                        - Upload photo
GET    /case-photos/{id}/                   - Get photo detail
DELETE /case-photos/{id}/                   - Delete photo
POST   /case-photos/reorder/                - Reorder photos

DEPLOYMENT LOGS (NEW):
------------------------------------
GET    /deployment-logs/                    - List logs (?case_id=xxx to filter)
GET    /deployment-logs/{id}/               - Get log detail
"""