# Generated by Django 4.2.19 on 2025-07-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorialsite',
            name='domain_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('error', 'Error')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='memorialsite',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memorialsite',
            name='subdomain',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
