# Generated by Django 4.2.19 on 2025-07-17 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title for the case', max_length=100)),
                ('victim_name', models.CharField(help_text='Full name of the victim', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='case_photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, help_text='Where the incident occurred', max_length=255)),
                ('case_number', models.CharField(blank=True, help_text='Official case number', max_length=100)),
                ('investigating_department', models.CharField(blank=True, max_length=255)),
                ('detective_contact', models.CharField(blank=True, help_text="Detective's contact info", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Case bio or story')),
                ('media_links', models.TextField(blank=True, help_text='Comma-separated URLs or media links')),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Reward amount in USD (ex: 5000.00)', max_digits=10, null=True)),
                ('reward_offered', models.CharField(blank=True, help_text="Reward details/terms (e.g., 'For info leading to arrest/conviction. Subject to verification.')", max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('subdomain', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('domain_status', models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('error', 'Error')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
