# Generated by Django 4.2.19 on 2025-09-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='crime_type',
            field=models.CharField(blank=True, help_text='Alias for case_type for backward compatibility', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='last_seen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='last_seen_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='last_seen_wearing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='last_seen_with',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='planned_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='transportation_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casephoto',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
