# Generated by Django 4.2.19 on 2025-07-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_first_name_case_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='crime_type',
            field=models.CharField(blank=True, help_text='Category of crime (e.g. Homicide, Missing)', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='detective_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='detective_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='detective_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='relation',
            field=models.CharField(blank=True, help_text='Your relationship to the victim (e.g. sister, friend)', max_length=100),
        ),
    ]
