# Generated by Django 4.2.19 on 2025-09-21 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_case_crime_type_case_last_seen_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigatorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('badge_number', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(max_length=255)),
                ('officer_name', models.CharField(max_length=255)),
                ('access_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigator_invites', to='cases.case')),
            ],
            options={
                'db_table': 'investigator_invites',
            },
        ),
        migrations.CreateModel(
            name='CaseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('viewer', 'View Only'), ('tips_only', 'Tips Only'), ('investigator', 'Full Investigation Access'), ('collaborator', 'Collaborator')], default='viewer', max_length=20)),
                ('can_view_tips', models.BooleanField(default=True)),
                ('can_view_tracking', models.BooleanField(default=False)),
                ('can_view_personal_info', models.BooleanField(default=False)),
                ('can_view_evidence', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('can_contact_family', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_message', models.TextField(blank=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='cases.case')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_access',
                'unique_together': {('case', 'user')},
            },
        ),
    ]
