# Generated by Django 4.2.19 on 2025-07-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_crime_type_case_detective_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='layout',
            field=models.JSONField(default=list, help_text='Widget layout configuration for the site'),
        ),
        migrations.AddField(
            model_name='case',
            name='template',
            field=models.CharField(blank=True, default='standard_vigil', help_text='Selected site template', max_length=100),
        ),
    ]
