# Generated by Django 4.2.19 on 2025-09-22 02:23

import cases.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0003_investigatorinvite_caseaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEOInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=cases.models.generate_leo_invite_code, max_length=12, unique=True)),
                ('officer_name', models.CharField(max_length=255)),
                ('officer_email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=255)),
                ('badge_number', models.CharField(blank=True, max_length=50)),
                ('access_config', models.JSONField(default=dict, help_text='Permissions configuration for this LEO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leo_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='investigatorinvite',
            name='case',
        ),
        migrations.AddField(
            model_name='case',
            name='archived',
            field=models.BooleanField(default=False, help_text='Archive case instead of deleting'),
        ),
        migrations.AddField(
            model_name='case',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseaccess',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caseaccess',
            name='actions_log',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='caseaccess',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='template_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores all template-specific customizations'),
        ),
        migrations.AlterField(
            model_name='caseaccess',
            name='access_level',
            field=models.CharField(choices=[('viewer', 'View Only'), ('tips_only', 'Tips Only'), ('leo', 'Law Enforcement Officer'), ('private_investigator', 'Private Investigator'), ('advocate', 'Victim Advocate'), ('collaborator', 'Family Collaborator')], default='viewer', max_length=30),
        ),
        migrations.AlterField(
            model_name='templateregistry',
            name='schema',
            field=models.JSONField(default=dict, help_text='UNIQUE schema for this template defining customizable sections'),
        ),
        migrations.AddIndex(
            model_name='caseaccess',
            index=models.Index(fields=['case', 'user'], name='case_access_case_id_4b7116_idx'),
        ),
        migrations.AddIndex(
            model_name='caseaccess',
            index=models.Index(fields=['access_level', 'accepted'], name='case_access_access__1c662d_idx'),
        ),
        migrations.DeleteModel(
            name='InvestigatorInvite',
        ),
        migrations.AddField(
            model_name='leoinvite',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leo_invites', to='cases.case'),
        ),
        migrations.AddField(
            model_name='leoinvite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_leo_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leoinvite',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_leo_invite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leoinvite',
            index=models.Index(fields=['invite_code'], name='leo_invites_invite__44e127_idx'),
        ),
        migrations.AddIndex(
            model_name='leoinvite',
            index=models.Index(fields=['case', '-created_at'], name='leo_invites_case_id_a8056c_idx'),
        ),
    ]
