# Generated by Django 4.2.19 on 2025-10-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_leoinvite_remove_investigatorinvite_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='incident_city',
            field=models.CharField(blank=True, help_text='City where the incident occurred', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_state',
            field=models.CharField(blank=True, help_text='State/Province where the incident occurred', max_length=50),
        ),
    ]
