# Generated by Django 4.2.19 on 2025-07-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_layout_case_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='logo',
            field=models.ImageField(blank=True, help_text="Custom logo for the victim's site", null=True, upload_to='case_logos/'),
        ),
        migrations.AddField(
            model_name='case',
            name='logo_gallery_id',
            field=models.CharField(blank=True, help_text='ID/reference for a pre-made gallery logo', max_length=100, null=True),
        ),
    ]
