# Generated by Django 4.2.19 on 2025-10-21 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_case_incident_city_case_incident_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(max_length=254)),
                ('invitee_name', models.CharField(max_length=200)),
                ('access_type', models.CharField(choices=[('police', 'Law Enforcement'), ('investigator', 'Private Investigator'), ('advocate', 'Victim Advocate'), ('family', 'Family Member'), ('other', 'Other')], max_length=20)),
                ('subject_line', models.CharField(max_length=255)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('invitation_code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_case_invitations', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='cases.case')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_case_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invitation_code'], name='case_invita_invitat_9e9936_idx'), models.Index(fields=['case', 'status'], name='case_invita_case_id_0122c2_idx')],
                'unique_together': {('case', 'invitee_email')},
            },
        ),
    ]
