# Generated by Django 4.2.19 on 2025-07-31 00:14

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_logo_case_logo_gallery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='logo',
            field=models.ImageField(blank=True, help_text="Custom logo for the victim's site", null=True, upload_to=cases.models.case_logo_upload_path),
        ),
    ]
