# Generated by Django 4.2.19 on 2025-10-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_caseinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseinvitation',
            name='access_type',
        ),
        migrations.AddField(
            model_name='caseinvitation',
            name='can_export_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caseinvitation',
            name='can_view_personal_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caseinvitation',
            name='can_view_tips',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caseinvitation',
            name='can_view_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caseinvitation',
            name='invitation_type',
            field=models.CharField(choices=[('police', 'Law Enforcement'), ('investigator', 'Private Investigator'), ('advocate', 'Victim Advocate'), ('family', 'Family Member'), ('other', 'Other')], default='other', help_text="Role they'll have when they sign up", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caseinvitation',
            name='invitee_account_type',
            field=models.CharField(choices=[('unverified', 'Unverified User'), ('verified', 'Verified Family Member'), ('helper', 'Community Helper'), ('detective', 'Law Enforcement'), ('advocate', 'Victim Advocate'), ('admin', 'Administrator')], default='unverified', help_text="Account type they'll receive when signing up", max_length=20),
        ),
        migrations.AddField(
            model_name='caseinvitation',
            name='read_only',
            field=models.BooleanField(default=True, help_text='If True, user can only view, not edit'),
        ),
    ]
