# Generated by Django 4.2.19 on 2026-03-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_remove_caseinvitation_access_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('active', 'Active'), ('solved', 'Solved'), ('cold_case', 'Cold Case'), ('closed', 'Closed')], default='active', help_text='Investigation status of the case', max_length=20),
        ),
    ]
