# Generated by Django 4.2.19 on 2026-03-27 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_add_case_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('incident', 'Incident'), ('investigation', 'Investigation'), ('arrest', 'Arrest'), ('court', 'Court'), ('memorial', 'Memorial'), ('media', 'Media Coverage'), ('sighting', 'Sighting'), ('other', 'Other')], default='other', max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('is_major', models.BooleanField(default=False, help_text='Highlight as a major event on the timeline')),
                ('order', models.IntegerField(default=0, help_text='Manual sort order override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.case')),
            ],
            options={
                'db_table': 'case_timeline_events',
                'ordering': ['date', 'time', 'order'],
                'indexes': [models.Index(fields=['case', 'date'], name='case_timeli_case_id_8bcb97_idx')],
            },
        ),
    ]
